 
 import { StyleSheet } from 'react-native';
 
 export const styles = StyleSheet.create({
    textInput: {
        backgroundColor: '#FFFFFF',
        borderWidth: 2,
        borderColor: '#0000FF',
        borderRadius: 25,
        paddingVertical: 16,
        paddingHorizontal: 24,
        fontSize: 14,
        textAlign: 'center',
        color: '#333',
        marginBottom: 16,
    },
    fileInput: {
        backgroundColor: '#FFFFFF',
        borderWidth: 2,
        borderColor: '#0000FF',
        borderRadius: 25,
        paddingVertical: 16,
        paddingHorizontal: 24,
        marginBottom: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    fileInputText: {
        fontSize: 14,
        color: '#999',
        textAlign: 'center',
        textTransform: 'uppercase',
    },
     backButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: '#0000FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: { fontSize: 28, fontWeight: 'bold', color: '#0000FF' },
  placeholder: { width: 56 },
  mainContent: { flex: 1, backgroundColor: '#0000FF' },
  scrollContent: { padding: 20, paddingTop: 40, paddingBottom: 40 },
  card: {
    backgroundColor: '#F5F5F5',
    borderRadius: 40,
    padding: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  cardTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#1A1A1A',
    marginBottom: 24,
  },
  
  submitButton: {
    backgroundColor: '#0000FF',
    borderRadius: 25,
    paddingVertical: 18,
    marginTop: 24,
    alignItems: 'center',
    shadowColor: '#0000FF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  submitButtonText: { color: '#FFFFFF', fontSize: 18, fontWeight: 'bold' },
   header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
});
