 import { StyleSheet } from 'react-native';
 
 export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  header: {
    backgroundColor: "#0000FF",
    paddingHorizontal: 24,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 12,
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#D1D5DB",
    borderWidth: 2,
    borderColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  avatarText: {
    fontSize: 20,
    fontWeight: "600",
    color: "#6B7280",
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  iconButton: {
    position: "relative",
    marginLeft: 16,
  },
  badge: {
    position: "absolute",
    top: -4,
    right: -4,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  badgeText: {
    fontSize: 10,
    fontWeight: "bold",
    color: "#0000FF",
  },
  mainContent: {
    flex: 1,
  },
  scrollContent: {
    padding: 24,
    paddingBottom: 120,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 48,
    borderWidth: 4,
    borderColor: "#0000FF",
    padding: 32,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  menuItem: {
    width: "30%",
    alignItems: "center",
    marginBottom: 24,
  },
  menuIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "#0000FF",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    position: "relative",
  },
  crossedLine: {
    position: "absolute",
    width: "100%",
    height: 2,
    backgroundColor: "#0000FF",
    transform: [{ rotate: "45deg" }],
  },
  menuLabel: {
    fontSize: 12,
    textAlign: "center",
    color: "#1F2937",
    fontWeight: "500",
    lineHeight: 16,
  },
  bottomNavContainer: {
    position: "absolute",
    bottom: 24,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  bottomNav: {
    backgroundColor: "#0000FF",
    borderRadius: 40,
    paddingHorizontal: 32,
    paddingVertical: 16,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  bottomNavItem: {
    alignItems: "center",
    marginHorizontal: 16,
  },
  bottomNavLabel: {
    fontSize: 11,
    color: "rgba(255, 255, 255, 0.6)",
  },
  bottomNavLabelActive: {
    color: "#FFFFFF",
    fontWeight: "600",
  },
});